# docker-Specify the compose version
version: "3"

services:
  app:
    #build: .
    image: pudding/docker-image-base:action-RSS-Fulltext-Docker-Image-20250524.163401
    tty: true
    volumes: 
      - ./output:/output/
      - ./cache:/cache/
      - ./config-json.js:/config-json.js
      - ./config-list.js:/config-list.js
